# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in mondial_connector.gemspec
gemspec

gem 'minitest', '~> 5.16'
gem 'rake', '~> 13.0'
gem 'rubocop', require: false

group :test do
  gem 'simplecov', require: false
end
